<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

//определяем правила валидации

$config = array(
			'family'=>array(
									array(
										'field'=>'family',
										'label'=>'lang:family',
										'rules'=>'trim|required|xss_clean|callback_check_employee'
									)
									),
			'checked'=>array(
									array(
										'field'=>'chk_id[]',
										'label'=>'lang:check',
										'rules'=>'callback_isset_value_chk'
									)
									),									

			'checkfamily'=>array(
									array(
										'field'=>'family',
										'label'=>'lang:family',
										'rules'=>'trim|required|xss_clean'
									),
									array(
										'field'=>'chk_id[]',
										'label'=>'lang:check',
										'rules'=>'callback_isset_value_chk'
									)
									),	

			'category'=>array(
									array(
										'field'=>'category',
										'label'=>'lang:category',
										'rules'=>'trim|required|xss_clean|callback_check_category'
									)
									),
			'checkcategory'=>array(
									array(
										'field'=>'category',
										'label'=>'lang:category',
										'rules'=>'trim|required|xss_clean'
									),
									array(
										'field'=>'chk_id[]',
										'label'=>'lang:check',
										'rules'=>'callback_isset_value_chk'
									)
									),	

			'rooms'=>array(
									array(
										'field'=>'room',
										'label'=>'lang:room',
										'rules'=>'trim|required|xss_clean|callback_check_room'
									)
									),
			'checkroom'=>array(
									array(
										'field'=>'room',
										'label'=>'lang:room',
										'rules'=>'trim|required|xss_clean'
									),
									array(
										'field'=>'chk_id[]',
										'label'=>'lang:check',
										'rules'=>'callback_isset_value_chk'
									)									
									),
			'assets'=>array(
									array(
										'field'=>'number_assets',
										'label'=>'lang:number_assets',
										'rules'=>'min_length[4]|max_length[10]|numeric|trim|required|xss_clean|callback_check_inv'
									),
									array(
										'field'=>'name_assets',
										'label'=>'lang:name_assets',
										'rules'=>'trim|required|xss_clean'
									),
									array(
										'field'=>'price_assets',
										'label'=>'lang:price_assets',
										'rules'=>'numeric|xss_clean|callback_check_empty'
									),
									array(
										'field'=>'amortization_assets',
										'label'=>'lang:amortization_assets',
										'rules'=>'numeric|xss_clean|callback_check_empty'
									),									
									array(
										'field'=>'date_assets',
										'label'=>'lang:date_assets',
										'rules'=>'trim|xss_clean|callback_check_empty_date|callback_check_date'
									)
									),
									
			'checkassets'=>array(
									array(
										'field'=>'number_assets',
										'label'=>'lang:number_assets',
										'rules'=>'min_length[4]|max_length[10]|numeric|trim|required|xss_clean'
									),
									array(
										'field'=>'name_assets',
										'label'=>'lang:name_assets',
										'rules'=>'trim|required|xss_clean'
									),
									array(
										'field'=>'price_assets',
										'label'=>'lang:price_assets',
										'rules'=>'numeric|trim|required|xss_clean'
									),
									array(
										'field'=>'amortization_assets',
										'label'=>'lang:amortization_assets',
										'rules'=>'numeric|trim|required|xss_clean'
									),									
									array(
										'field'=>'date_assets',
										'label'=>'lang:date_assets',
										'rules'=>'trim|required|xss_clean|callback_check_date'
									),
									array(
										'field'=>'chk_id[]',
										'label'=>'lang:check',
										'rules'=>'callback_isset_value_chk'
									)										
									),	
			'report'=>array(
									array(
										'field'=>'amount',
										'label'=>'lang:amount',
										'rules'=>'numeric|trim|required|xss_clean'
									)
									),																	
									
			'checkreport'=>array(
									array(
										'field'=>'amount',
										'label'=>'lang:amount',
										'rules'=>'numeric|trim|required|xss_clean'
									),
									array(
										'field'=>'chk_id[]',
										'label'=>'lang:check',
										'rules'=>'callback_isset_value_chk'
									)									
									),	
			'search'=>array(
									array(
										'field'=>'price1_search',
										'label'=>'lang:price1_search',
										'rules'=>'trim|numeric|callback_check_empty_price1'
									),
									array(
										'field'=>'price2_search',
										'label'=>'lang:price2_search',
										'rules'=>'trim|numeric|callback_check_empty_price2|callback_compare'
									),
									array(
										'field'=>'date1_search',
										'label'=>'lang:date1_search',
										'rules'=>'trim|callback_check_empty_date1|callback_check_date'
									),									
									array(
										'field'=>'date2_search',
										'label'=>'lang:date2_search',
										'rules'=>'trim|callback_check_empty_date2|callback_check_date|callback_compare_date'
									),
									array(
										'field'=>'chk_inv',
										'label'=>'lang:check',
										'rules'=>'callback_return_true'
									),
									array(
										'field'=>'chk_room',
										'label'=>'lang:check',
										'rules'=>'callback_return_true'
									),
									array(
										'field'=>'chk_fio',
										'label'=>'lang:check',
										'rules'=>'callback_return_true'
									),
									array(
										'field'=>'chk_cat',
										'label'=>'lang:check',
										'rules'=>'callback_return_true'
									),
									),


);


